name: umeng_ulink
description: 友盟 U-Link 深度链接 Flutter 插件，支持延迟深度链接、场景还原、邀请归因等功能
version: 1.0.0
homepage: https://github.com/CodeGather/umeng_ulink
repository: https://github.com/CodeGather/umeng_ulink
issue_tracker: https://github.com/CodeGather/umeng_ulink/issues
topics: [umeng, deeplink, ulink, invite, referral]

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codegather.umeng_ulink
        pluginClass: UmengUlinkPlugin
      ios:
        pluginClass: UmengUlinkPlugin
